### PR TITLE
Add repos for SCS Cluster Stacks

### PR DESCRIPTION
**Pull request by jschoone**
This PR adds the two new repositories regarding the SCS Cluster Stacks.
Basically these repositories initially represent the two Epics [issues/#321](https://github.com/SovereignCloudStack/issues/issues/321) and [issues/#326](https://github.com/SovereignCloudStack/issues/issues/326) but will certainly play a bigger role in future releases.

I decided to not use the prefix `k8s` in the name because it feels more serious for me and looks more like a product which is powered by Kubernetes not vice versa. Essentially same as e.g. OpenShift, Rancher, Tanzu...
But of course I am ready to discuss that.

### CODE REVIEW

**Comment by jschoone** [comment]
@maxwolfs and @fkr I don't get the PAT thingy, especially since GitHub has a new dance to create those. Means the pipelines will fail.
Since you both have valid PATs, could you (re)run the pipelines, provided that everyone is satisfied and there are enough approvals?

**Review by janiskemper — APPROVED** [review]

**Review by batistein — APPROVED** [review]

**Comment by jschoone** [comment]
Hi @fkr, I only see one of the two repos. DId I do something wrong on creating them or does the run need to run twice or something like that?

**Comment by fkr** [comment]
@jschoone the repos need to be initialized for the github-manager to run properly:

```
TASK [Apply repository cluster-stacks] *****************************************
fatal: [localhost]: FAILED! => {"changed": false, "errors": ["Repo cluster-stacks@SovereignCloudStack cannot be updated: {'url': 'https://api.github.com/repos/SovereignCloudStack/cluster-stacks', 'msg': 'HTTP Error 422: Unprocessable Entity', 'status': 422, 'body': b'{\"message\":\"Validation Failed\",\"errors\":[{\"message\":\"Cannot update default branch for an empty repository. Please init the repository and push first.\",\"resource\":\"Repository\",\"field\":\"default_branch\",\"code\":\"invalid\"}],\"documentation_url\":\"https://docs.github.com/rest/repos/repos#update-a-repository\"}'}"], "msg": "Failures occured", "repository": null}

PLAY RECAP *********************************************************************
localhost                  : ok=126  changed=2    unreachable=0    failed=1    skipped=29   rescued=0    ignored=0   
```

(from https://github.com/SovereignCloudStack/github-manager/actions/runs/5027772318/jobs/9017671190#step:7:379)

Once the repo is initialized, I can re-trigger the workflow.

**Comment by jschoone** [comment]
> @jschoone the repos need to be initialized for the github-manager to run properly:
> 
> ```
> TASK [Apply repository cluster-stacks] *****************************************
> fatal: [localhost]: FAILED! => {"changed": false, "errors": ["Repo cluster-stacks@SovereignCloudStack cannot be updated: {'url': 'https://api.github.com/repos/SovereignCloudStack/cluster-stacks', 'msg': 'HTTP Error 422: Unprocessable Entity', 'status': 422, 'body': b'{\"message\":\"Validation Failed\",\"errors\":[{\"message\":\"Cannot update default branch for an empty repository. Please init the repository and push first.\",\"resource\":\"Repository\",\"field\":\"default_branch\",\"code\":\"invalid\"}],\"documentation_url\":\"https://docs.github.com/rest/repos/repos#update-a-repository\"}'}"], "msg": "Failures occured", "repository": null}
> 
> PLAY RECAP *********************************************************************
> localhost                  : ok=126  changed=2    unreachable=0    failed=1    skipped=29   rescued=0    ignored=0   
> ```
> 
> (from https://github.com/SovereignCloudStack/github-manager/actions/runs/5027772318/jobs/9017671190#step:7:379)
> 
> Once the repo is initialized, I can re-trigger the workflow.

@fkr ah! Should be initialized now

**Pull request merged**
