### PR TITLE
Add container-images repository

### PR DESCRIPTION
**Pull request by berendt**

### CODE REVIEW

**Comment by jschoone** [comment]
Hi,
could you provide some description for what this repo is for?

**Comment by reqa** [comment]
> Hi, could you provide some description for what this repo is for?

See https://github.com/osism/testbed/pull/1775#issuecomment-1746663597

**Comment by berendt** [comment]
For container images for which you do not need a separate repo. Like this one: https://github.com/osism/container-images.

**Review by garloff — APPROVED** [review]
This should work

**Pull request merged**
