### PR TITLE
add standards repository

### PR DESCRIPTION
**Pull request by tibeer**
partly SovereignCloudStack/issues#235

Signed-off-by: Tim Beermann <beermann@osism.tech>

### CODE REVIEW

**Comment by itrich** [comment]
There is no initiated `standards` repository yet. Who is in charge of creating (and initiating) one?

**Comment by tibeer** [comment]
@itrich I thought the github action attached to this repository.

**Comment by itrich** [comment]
> @itrich I thought the github action attached to this repository.

Let's see what happens :grin:

**Comment by tibeer** [comment]
Worked. Still with an error, that the base-branch cannot be updated, but that's okay. The repository is now available.

**Pull request merged**
