### PR TITLE
rework to solve unforseen errors

### PR DESCRIPTION
**Pull request by scoopex**

### CODE REVIEW

**Comment by fkr** [comment]
@scoopex i think the repositories should be adjusted to default to main branches.

**Comment by scoopex** [comment]
> @scoopex i think the repositories should be adjusted to default to main branches.

I also thought about that, but:
They are just clones of other repositories, therefore i dropped that idea.

**Comment by fkr** [comment]
> > @scoopex i think the repositories should be adjusted to default to main branches.
> 
> 
> 
> I also thought about that, but:
> 
> They are just clones of other repositories, therefore i dropped that idea.

ah, thanks! didn't check that.

**Review by fkr — APPROVED** [review]
LGTM!

**Pull request merged**
