### PR TITLE
Make Jan Schoone admin, add Dirk Lossack to OSBA.

### PR DESCRIPTION
**Pull request by garloff**
Signed-off-by: Kurt Garloff <kurt@garloff.de>

### CODE REVIEW

**Comment by garloff** [comment]
For merging tomorrow morning!

**Review by itrich — APPROVED** [review]
LGTM!

**Comment by garloff** [comment]
I did not know about this /remind-me thing. Nice! THANKS!

**Comment by itrich** [comment]
> I did not know about this /remind-me thing. Nice! THANKS!

I added this one a while ago to keep track of needed changes, especially in regard of closing tenders. I'll add a small piece of documentation to <docs.scs.community> the next days.

**Pull request merged**
